# Generated by Django 3.2 on 2024-03-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apname', models.CharField(max_length=100)),
                ('apemail', models.CharField(max_length=200)),
                ('apphone', models.CharField(max_length=50)),
                ('apdepart', models.CharField(max_length=100)),
                ('apdate', models.CharField(max_length=100)),
                ('apdoctor', models.CharField(max_length=100)),
                ('apmessage', models.TextField()),
            ],
        ),
    ]
