# Generated by Django 3.2 on 2024-03-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_appointdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regfname', models.CharField(max_length=100)),
                ('reglname', models.CharField(max_length=100)),
                ('regemail', models.CharField(max_length=100)),
                ('regphone', models.CharField(max_length=50)),
            ],
        ),
    ]
